#define pul1 A0
#define pul2 A1
#define pul3 2
#define pul4 3
const int led1 = 4;
const int led2 = 5;
const int led3 = 6 ;
const int led4 = 7;
const int led5 = 8;
const int led6 = 9;
const int led7 = 10;
const int led8 = 11;
const int led9 = 12;
const int led10 = 13;
int estado1;
int estado2;
int estado3;
int estado4;
#define entrada() pinMode(pul1,INPUT)
#define entrada_2() pinMode(pul2,INPUT)
#define entrada_3() pinMode(pul3,INPUT)
# define entrada_4() pinMode(pul4,INPUT)
#define salida_1() pinMode(led1,OUTPUT)
#define salida_2() pinMode(led2,OUTPUT)
#define salida_3() pinMode(led3,OUTPUT)
#define salida_4() pinMode(led4,OUTPUT)
#define salida_5() pinMode(led5,OUTPUT)
#define salida_6() pinMode(led6,OUTPUT)
#define salida_7() pinMode(led7,OUTPUT)
#define salida_8() pinMode(led8,OUTPUT)
#define salida_9() pinMode(led9,OUTPUT)
#define salida_10() pinMode(led10,OUTPUT)
void setup(){
Serial.begin(9600);
entrada();
entrada_2();
entrada_3();
entrada_4();
salida_1();
salida_2();
salida_3();
salida_4();
salida_5();
salida_6();
salida_7();
salida_8();
salida_9();
salida_10();
}
void loop(){
Serial.println(estado1);
Serial.println(estado2);
Serial.println(estado3);
Serial.println(estado4);
estado1 = digitalRead(pul1);
if(estado1 == 1){ 
  digitalWrite(led1, HIGH);                   
  digitalWrite(led10, HIGH);
  delay(100);
  digitalWrite(led2, HIGH);                   
  digitalWrite(led9, HIGH);
  delay(100);
  digitalWrite(led3, HIGH);                   
  digitalWrite(led8, HIGH);
  delay(100);
  digitalWrite(led4, HIGH);                   
  digitalWrite(led7, HIGH);
  delay(100);
  digitalWrite(led5, HIGH);                   
  digitalWrite(led6, HIGH);
  delay(100);
  digitalWrite(led1,LOW);
  digitalWrite(led2,LOW);
  digitalWrite(led3,LOW);
  digitalWrite(led4,LOW);
  digitalWrite(led5,LOW);
  digitalWrite(led6,LOW);
  digitalWrite(led7,LOW);
  digitalWrite(led8,LOW);
  digitalWrite(led9,LOW);
  digitalWrite(led10,LOW);
  delay(100);
  digitalWrite(led1, HIGH);                   
  digitalWrite(led10, HIGH);
  delay(100);
  digitalWrite(led2, HIGH);                   
  digitalWrite(led9, HIGH);
  delay(100);
  digitalWrite(led3, HIGH);                   
  digitalWrite(led8, HIGH);
  delay(100);
  digitalWrite(led4, HIGH);                   
  digitalWrite(led7, HIGH);
  delay(100);
  digitalWrite(led5, HIGH);                   
  digitalWrite(led6, HIGH);
  delay(100);
  digitalWrite(led1,LOW);
  digitalWrite(led2,LOW);
  digitalWrite(led3,LOW);
  digitalWrite(led4,LOW);
  digitalWrite(led5,LOW);
  digitalWrite(led6,LOW);
  digitalWrite(led7,LOW);
  digitalWrite(led8,LOW);
  digitalWrite(led9,LOW);
  digitalWrite(led10,LOW);
  delay(100);
  digitalWrite(led1, HIGH);                   
  digitalWrite(led10, HIGH);
  delay(100);
  digitalWrite(led2, HIGH);                   
  digitalWrite(led9, HIGH);
  delay(100);
  digitalWrite(led3, HIGH);                   
  digitalWrite(led8, HIGH);
  delay(100);
  digitalWrite(led4, HIGH);                   
  digitalWrite(led7, HIGH);
  delay(100);
  digitalWrite(led5, HIGH);                   
  digitalWrite(led6, HIGH);
  delay(100);
  digitalWrite(led1,LOW);
  digitalWrite(led2,LOW);
  digitalWrite(led3,LOW);
  digitalWrite(led4,LOW);
  digitalWrite(led5,LOW);
  digitalWrite(led6,LOW);
  digitalWrite(led7,LOW);
  digitalWrite(led8,LOW);
  digitalWrite(led9,LOW);
  digitalWrite(led10,LOW);
  delay(100);
  digitalWrite(led1, HIGH);                   
  digitalWrite(led10, HIGH);
  delay(100);
  digitalWrite(led2, HIGH);                   
  digitalWrite(led9, HIGH);
  delay(100);
  digitalWrite(led3, HIGH);                   
  digitalWrite(led8, HIGH);
  delay(100);
  digitalWrite(led4, HIGH);                   
  digitalWrite(led7, HIGH);
  delay(100);
  digitalWrite(led5, HIGH);                   
  digitalWrite(led6, HIGH);
  delay(100);
  digitalWrite(led1,LOW);
  digitalWrite(led2,LOW);
  digitalWrite(led3,LOW);
  digitalWrite(led4,LOW);
  digitalWrite(led5,LOW);
  digitalWrite(led6,LOW);
  digitalWrite(led7,LOW);
  digitalWrite(led8,LOW);
  digitalWrite(led9,LOW);
  digitalWrite(led10,LOW);
  delay(100);
}
estado2 = digitalRead(pul2);
if(estado2 == 0){
  digitalWrite(led5, HIGH);                   
  digitalWrite(led6, HIGH);
  delay(100);
  digitalWrite(led4, HIGH);                   
  digitalWrite(led7, HIGH);
  delay(100);
  digitalWrite(led3, HIGH);                   
  digitalWrite(led8, HIGH);
  delay(100);
  digitalWrite(led2, HIGH);                   
  digitalWrite(led9, HIGH);
  delay(100);
  digitalWrite(led1, HIGH);                   
  digitalWrite(led10, HIGH);
  delay(100);
  digitalWrite(led1,LOW);
  digitalWrite(led2,LOW);
  digitalWrite(led3,LOW);
  digitalWrite(led4,LOW);
  digitalWrite(led5,LOW);
  digitalWrite(led6,LOW);
  digitalWrite(led7,LOW);
  digitalWrite(led8,LOW);
  digitalWrite(led9,LOW);
  digitalWrite(led10,LOW);
  delay(100);
  digitalWrite(led5, HIGH);                   
  digitalWrite(led6, HIGH);
  delay(100);
  digitalWrite(led4, HIGH);                   
  digitalWrite(led7, HIGH);
  delay(100);
  digitalWrite(led3, HIGH);                   
  digitalWrite(led8, HIGH);
  delay(100);
  digitalWrite(led2, HIGH);                   
  digitalWrite(led9, HIGH);
  delay(100);
  digitalWrite(led1, HIGH);                   
  digitalWrite(led10, HIGH);
  delay(100);
  digitalWrite(led1,LOW);
  digitalWrite(led2,LOW);
  digitalWrite(led3,LOW);
  digitalWrite(led4,LOW);
  digitalWrite(led5,LOW);
  digitalWrite(led6,LOW);
  digitalWrite(led7,LOW);
  digitalWrite(led8,LOW);
  digitalWrite(led9,LOW);
  digitalWrite(led10,LOW);
  delay(100);
  digitalWrite(led5, HIGH);                   
  digitalWrite(led6, HIGH);
  delay(100);
  digitalWrite(led4, HIGH);                   
  digitalWrite(led7, HIGH);
  delay(100);
  digitalWrite(led3, HIGH);                   
  digitalWrite(led8, HIGH);
  delay(100);
  digitalWrite(led2, HIGH);                   
  digitalWrite(led9, HIGH);
  delay(100);
  digitalWrite(led1, HIGH);                   
  digitalWrite(led10, HIGH);
  delay(100);
  digitalWrite(led1,LOW);
  digitalWrite(led2,LOW);
  digitalWrite(led3,LOW);
  digitalWrite(led4,LOW);
  digitalWrite(led5,LOW);
  digitalWrite(led6,LOW);
  digitalWrite(led7,LOW);
  digitalWrite(led8,LOW);
  digitalWrite(led9,LOW);
  digitalWrite(led10,LOW);
  delay(100);
  digitalWrite(led5, HIGH);                   
  digitalWrite(led6, HIGH);
  delay(100);
  digitalWrite(led4, HIGH);                   
  digitalWrite(led7, HIGH);
  delay(100);
  digitalWrite(led3, HIGH);                   
  digitalWrite(led8, HIGH);
  delay(100);
  digitalWrite(led2, HIGH);                   
  digitalWrite(led9, HIGH);
  delay(100);
  digitalWrite(led1, HIGH);                   
  digitalWrite(led10, HIGH);
  delay(100);
  digitalWrite(led1,LOW);
  digitalWrite(led2,LOW);
  digitalWrite(led3,LOW);
  digitalWrite(led4,LOW);
  digitalWrite(led5,LOW);
  digitalWrite(led6,LOW);
  digitalWrite(led7,LOW);
  digitalWrite(led8,LOW);
  digitalWrite(led9,LOW);
  digitalWrite(led10,LOW);
  delay(100);
}
estado3 = digitalRead(pul3);
if(estado3 == 1){
  digitalWrite(led1,HIGH);
  delay(10);
  digitalWrite(led2,HIGH);
  delay(10);
  digitalWrite(led3,HIGH);
  delay(10);
  digitalWrite(led4,HIGH);
  delay(10);
  digitalWrite(led5,HIGH);
  delay(10);
  digitalWrite(led6,HIGH);
  delay(10);
  digitalWrite(led7,HIGH);
  delay(10);
  digitalWrite(led8,HIGH);
  delay(10);
  digitalWrite(led9,HIGH);
  delay(10);
  digitalWrite(led10,HIGH);
  delay(10);
  digitalWrite(led1,LOW);
  digitalWrite(led2,LOW);
  digitalWrite(led3,LOW);
  digitalWrite(led4,LOW);
  digitalWrite(led5,LOW);
  digitalWrite(led6,LOW);
  digitalWrite(led7,LOW);
  digitalWrite(led8,LOW);
  digitalWrite(led9,LOW);
  digitalWrite(led10,LOW);
  delay(100);
  digitalWrite(led1,HIGH);
  delay(10);
  digitalWrite(led2,HIGH);
  delay(10);
  digitalWrite(led3,HIGH);
  delay(10);
  digitalWrite(led4,HIGH);
  delay(10);
  digitalWrite(led5,HIGH);
  delay(10);
  digitalWrite(led6,HIGH);
  delay(10);
  digitalWrite(led7,HIGH);
  delay(10);
  digitalWrite(led8,HIGH);
  delay(10);
  digitalWrite(led9,HIGH);
  delay(10);
  digitalWrite(led10,HIGH);
  delay(10);
  digitalWrite(led1,LOW);
  digitalWrite(led2,LOW);
  digitalWrite(led3,LOW);
  digitalWrite(led4,LOW);
  digitalWrite(led5,LOW);
  digitalWrite(led6,LOW);
  digitalWrite(led7,LOW);
  digitalWrite(led8,LOW);
  digitalWrite(led9,LOW);
  digitalWrite(led10,LOW);
  delay(100);
  digitalWrite(led1,HIGH);
  delay(10);
  digitalWrite(led2,HIGH);
  delay(10);
  digitalWrite(led3,HIGH);
  delay(10);
  digitalWrite(led4,HIGH);
  delay(10);
  digitalWrite(led5,HIGH);
  delay(10);
  digitalWrite(led6,HIGH);
  delay(10);
  digitalWrite(led7,HIGH);
  delay(10);
  digitalWrite(led8,HIGH);
  delay(10);
  digitalWrite(led9,HIGH);
  delay(10);
  digitalWrite(led10,HIGH);
  delay(10);
  digitalWrite(led1,LOW);
  digitalWrite(led2,LOW);
  digitalWrite(led3,LOW);
  digitalWrite(led4,LOW);
  digitalWrite(led5,LOW);
  digitalWrite(led6,LOW);
  digitalWrite(led7,LOW);
  digitalWrite(led8,LOW);
  digitalWrite(led9,LOW);
  digitalWrite(led10,LOW);
  delay(100);
  digitalWrite(led1,HIGH);
  delay(10);
  digitalWrite(led2,HIGH);
  delay(10);
  digitalWrite(led3,HIGH);
  delay(10);
  digitalWrite(led4,HIGH);
  delay(10);
  digitalWrite(led5,HIGH);
  delay(10);
  digitalWrite(led6,HIGH);
  delay(10);
  digitalWrite(led7,HIGH);
  delay(10);
  digitalWrite(led8,HIGH);
  delay(10);
  digitalWrite(led9,HIGH);
  delay(10);
  digitalWrite(led10,HIGH);
  delay(10);
  digitalWrite(led1,LOW);
  digitalWrite(led2,LOW);
  digitalWrite(led3,LOW);
  digitalWrite(led4,LOW);
  digitalWrite(led5,LOW);
  digitalWrite(led6,LOW);
  digitalWrite(led7,LOW);
  digitalWrite(led8,LOW);
  digitalWrite(led9,LOW);
  digitalWrite(led10,LOW);
  delay(100);
}
estado4 = digitalRead(pul4);
if(estado4 == 1){
  digitalWrite(led10,HIGH);
  delay(10);
  digitalWrite(led9,HIGH);
  delay(10);
  digitalWrite(led8,HIGH);
  delay(10);
  digitalWrite(led7,HIGH);
  delay(10);
  digitalWrite(led6,HIGH);
  delay(10);
  digitalWrite(led5,HIGH);
  delay(10);
  digitalWrite(led4,HIGH);
  delay(10);
  digitalWrite(led3,HIGH);
  delay(10);
  digitalWrite(led2,HIGH);
  delay(10);
  digitalWrite(led1,HIGH);
  delay(10);
  digitalWrite(led10,LOW);
  digitalWrite(led9,LOW);
  digitalWrite(led8,LOW);
  digitalWrite(led7,LOW);
  digitalWrite(led6,LOW);
  digitalWrite(led5,LOW);
  digitalWrite(led4,LOW);
  digitalWrite(led3,LOW);
  digitalWrite(led2,LOW);
  digitalWrite(led1,LOW);
  delay(100);
  digitalWrite(led10,HIGH);
  delay(10);
  digitalWrite(led9,HIGH);
  delay(10);
  digitalWrite(led8,HIGH);
  delay(10);
  digitalWrite(led7,HIGH);
  delay(10);
  digitalWrite(led6,HIGH);
  delay(10);
  digitalWrite(led5,HIGH);
  delay(10);
  digitalWrite(led4,HIGH);
  delay(10);
  digitalWrite(led3,HIGH);
  delay(10);
  digitalWrite(led2,HIGH);
  delay(10);
  digitalWrite(led1,HIGH);
  delay(10);
  digitalWrite(led10,LOW);
  digitalWrite(led9,LOW);
  digitalWrite(led8,LOW);
  digitalWrite(led7,LOW);
  digitalWrite(led6,LOW);
  digitalWrite(led5,LOW);
  digitalWrite(led4,LOW);
  digitalWrite(led3,LOW);
  digitalWrite(led2,LOW);
  digitalWrite(led1,LOW);
  delay(100);
  digitalWrite(led10,HIGH);
  delay(10);
  digitalWrite(led9,HIGH);
  delay(10);
  digitalWrite(led8,HIGH);
  delay(10);
  digitalWrite(led7,HIGH);
  delay(10);
  digitalWrite(led6,HIGH);
  delay(10);
  digitalWrite(led5,HIGH);
  delay(10);
  digitalWrite(led4,HIGH);
  delay(10);
  digitalWrite(led3,HIGH);
  delay(10);
  digitalWrite(led2,HIGH);
  delay(10);
  digitalWrite(led1,HIGH);
  delay(10);
  digitalWrite(led10,LOW);
  digitalWrite(led9,LOW);
  digitalWrite(led8,LOW);
  digitalWrite(led7,LOW);
  digitalWrite(led6,LOW);
  digitalWrite(led5,LOW);
  digitalWrite(led4,LOW);
  digitalWrite(led3,LOW);
  digitalWrite(led2,LOW);
  digitalWrite(led1,LOW);
  delay(100);
  digitalWrite(led10,HIGH);
  delay(10);
  digitalWrite(led9,HIGH);
  delay(10);
  digitalWrite(led8,HIGH);
  delay(10);
  digitalWrite(led7,HIGH);
  delay(10);
  digitalWrite(led6,HIGH);
  delay(10);
  digitalWrite(led5,HIGH);
  delay(10);
  digitalWrite(led4,HIGH);
  delay(10);
  digitalWrite(led3,HIGH);
  delay(10);
  digitalWrite(led2,HIGH);
  delay(10);
  digitalWrite(led1,HIGH);
  delay(10);
  digitalWrite(led10,LOW);
  digitalWrite(led9,LOW);
  digitalWrite(led8,LOW);
  digitalWrite(led7,LOW);
  digitalWrite(led6,LOW);
  digitalWrite(led5,LOW);
  digitalWrite(led4,LOW);
  digitalWrite(led3,LOW);
  digitalWrite(led2,LOW);
  digitalWrite(led1,LOW);
  delay(100);
}
}